project:
  type: book
  output-dir: docs
website:
  comments:
      hypothesis:
        theme: clean
        openSidebar: false
book:
  title: HSMA - Programming in Python
  subtitle: An introduction to writing code in Python - from scratch!
  author: Dan Chalk and Sammi Rosser
  date: 14/05/2024
  chapters:
  - index.qmd
  - how_to_use_book.qmd
  - part: "Programming Concepts"
    chapters:
    - intro_to_programming_concepts.qmd
  # - part: "Using VSCode and Anaconda"
  #   chapters:
  #   - initial_vscode_setup.qmd
  #   - running_python_files.qmd
  #   - running_jupyter_notebooks.qmd
  #   - creating_environments_anaconda.qmd
  #   - creating_environments_python.qmd
  - part: "Your First Steps in Python"
    chapters:
    - intro_to_python.qmd
    - printing.qmd
    - variables.qmd
    - fstrings.qmd
    - user_input_casting.qmd
    - mathematical_operators.qmd
    - exercise_10_years_forward.qmd
  - part: "Your Next Python Skills"
    chapters:
    - comments.qmd
    - conditional_logic.qmd
    - exercise_conditional_logic_etc.qmd
  - part: "Loops, Lists and Dictionaries"
    chapters:
    - loops.qmd
    - exercise_loops.qmd
    - lists.qmd
    - list_comprehensions.qmd
    - dictionaries.qmd
    - exercise_lists_dictionaries.qmd
  - part: "An Introduction to Libraries"
    chapters:
    - importing_packages.qmd
    - the_random_library.qmd
    - exercise_smarter_dan_10.qmd
    - exercise_coding_challenge_1.qmd
  - part: "Functions, Files and error Handling"
    chapters:
    - functions.qmd
    - exercise_functions.qmd
    - exception_handling.qmd
    - file_handling.qmd
    - exercise_exception_and_file_handling.qmd
  - part: "Numpy"
    chapters:
    - intro_to_numpy.qmd
    - using_numpy.qmd
    - numpy_features.qmd
    - exercise_numpy.qmd
  - part: "Pandas"
    chapters:
    - intro_to_pandas.qmd
    - pandas_indexing.qmd
    - extending_joining_dataframes.qmd
    - removing_data_pandas.qmd
    - aggregating_pandas.qmd
    - sorting_previewing_more_pandas.qmd
    - exercise_pandas.qmd
  - part: "Object-Oriented Python"
    chapters:
    - recap_oop.qmd
    - intro_to_oopp.qmd
    - inheritance.qmd
    - reusability.qmd
  - part: "Graphs with matplotlib"
    chapters:
    - intro_to_matplotlib.qmd
    - matplotlib_chart_types.qmd
    - other_plotting_libraries.qmd
  - cheatsheets.qmd
  - further_reading.qmd
  cover-image: cover.jpeg
  favicon: resources/logos/hsma_logo_transparent_background_large.png
  search: true
  page-navigation: true
  back-to-top-navigation: true
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
  navbar:
    search: false
    background: '#8A1E1E'
    right:
      - icon: github
        href: https://github.com/hsma-programme/
        aria-label: GitHub
      - icon: youtube
        href: https://www.youtube.com/@hsma/
        aria-label: YouTube
      - icon: globe2
        href: https://sites.google.com/nihr.ac.uk/hsma/introduction-to-hsma
        aria-label: Website
      - icon: book
        href: https://github.com/Bergam0t/hsma6_intro_to_python_book
        aria-label: BookRepository
  sidebar:
    search: true
    style: docked
    logo: resources/logos/hsma_logo_transparent_background_large.png
    background: '#111111'
  open-graph: true
  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: dark
bibliography: references.bib
format:
  html:
    css: include/webex.css
    include-after-body: include/webex.js
    theme:
      dark:
      - darkly
      - theme-dark.scss
      - resources/fonts/css/lexend.css
      light:
      - flatly
      - theme-light.scss
      - resources/fonts/css/lexend.css
    grid:
      sidebar-width: 250px
