project:
  type: book
  output-dir: docs
book:
  title: HSMA - Programming in Python
  subtitle: An introduction to writing code in Python - from scratch!
  author: Dan Chalk and Sammi Rosser
  date: 14/05/2024
  chapters:
  - index.qmd
  - intro.qmd
  - part: "Programming Concepts"
    chapters:
    - intro_to_programming_concepts.qmd
  - part: "Your First Steps in Python"
    chapters:
    - intro_to_python.qmd
    - printing.qmd
    - variables.qmd
    - fstrings.qmd
    - user_input_casting.qmd
    - mathematical_operators.qmd
    - exercise_10_years_forward.qmd
  - part: "Your Next Python Skills"
    chapters:
    - comments.qmd
    - conditional_logic.qmd
    - exercise_conditional_logic_etc.qmd
  - part: "Loops, Lists and Dictionaries"
    chapters:
    - loops.qmd
    - exercise_loops.qmd
    - lists.qmd
    - list_comprehensions.qmd
    - dictionaries.qmd
    - exercise_lists_dictionaries.qmd
  - part: "An Introduction to Libraries"
    chapters:
    - importing_packages.qmd
    - the_random_library.qmd
    - exercise_smarter_dan_10.qmd
    - exercise_coding_challenge_1.qmd
  - part: "Functions, Files and error Handling"
    chapters:
    - functions.qmd
    - exercise_functions.qmd
    - exception_handling.qmd
    - file_handling.qmd
    - exercise_exception_handling.qmd
  - part: "Numpy"
    chapters:
    - intro_to_numpy.qmd
  - part: "Pandas"
    chapters:
    - intro_to_pandas.qmd
  - further_reading.qmd
  - references.qmd
  cover-image: resources/logos/hsma_logo_transparent_background_large.png
  favicon: resources/logos/hsma_logo_transparent_background_large.png
  search: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    search: false
    background: '#8A1E1E'
  sidebar:
    search: true
    style: docked
    logo: resources/logos/hsma_logo_transparent_background_large.png
    background: '#111111'
  open-graph: true
  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: dark
bibliography: references.bib
format:
  html:
    css: include/webex.css
    include-after-body: include/webex.js
    theme:
      dark:
      - darkly
      - theme-dark.scss
      - resources/fonts/css/lexend.css
      light:
      - flatly
      - theme-light.scss
      - resources/fonts/css/lexend.css
    grid:
      sidebar-width: 250px
