project:
  type: book
book:
  title: HSMA - Programming in Python
  subtitle: An introduction to writing code in Python - from scratch!
  author: Dan Chalk and Sammi Rosser
  date: 14/05/2024
  chapters:
  - index.qmd
  - intro.qmd
  - part: "Part 1 - Programming Concepts"
    chapters:
    - intro_to_programming_concepts.qmd
  - part: "Part 2 - Your First Steps in Python"
    chapters:
    - variables.qmd
  - part: "Functions"
    chapters:
    - functions.qmd
  - part: "Numpy"
    chapters:
    - intro_to_numpy.qmd
  - part: "Pandas"
    chapters:
    - intro_to_pandas.qmd
  - further_reading.qmd
  - references.qmd
  cover-image: resources/logos/hsma_logo_transparent_background_large.png
  favicon: resources/logos/hsma_logo_transparent_background_large.png
  search: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    search: false
    background: '#8A1E1E'
  sidebar:
    search: true
    style: docked
    logo: resources/logos/hsma_logo_transparent_background_large.png
    background: '#111111'
  open-graph: true
  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: dark
bibliography: references.bib
format:
  html:
    css: include/webex.css
    include-after-body: include/webex.js
    theme:
      dark:
      - darkly
      - theme-dark.scss
      - resources/fonts/css/lexend.css
      light:
      - flatly
      - theme-light.scss
      - resources/fonts/css/lexend.css
    grid:
      sidebar-width: 250px
